name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-ubuntu-tests:
    timeout-minutes: 15
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: VirtusLab/scala-cli-setup@07b6783a2d71fbf9e834faa234cd51626d76cba5
      with:
        jvm: "temurin:17"
    - name: Run tests
      run: ./mill -i build-module.test

  build-macos-tests:
    timeout-minutes: 15
    runs-on: "macos-latest"
    steps:
    - name: Run tests
      run: ./mill -i build-module.test

  build-windows-tests:
    timeout-minutes: 15
    runs-on: "windows-latest"
    steps:
    - name: Run tests
      run: ./mill -i build-module.test
